### ISSUE TITLE
Weapons Mod Available for 1.20.1

### ISSUE THREAD

**Issue by JenniferDevelopez** [byteManiak/MCQuake3#3]
Could you make a craftable weapons pack for Forge so we can add the weapons to the vanilla game. Perhaps instead of ammo, just the same durability system as the default weapons in minecraft?

**Comment by byteManiak** [comment]
Hi. Sorry, this is not a Forge mod and I don't have plans to port to 1.20.x yet either. Also the weapon models require GeckoLib so porting to vanilla is not possible without recreating all models from scratch.
