### ISSUE TITLE
Rocket Launcher doesn't fire from exact center

### ISSUE THREAD

**Issue by MiruCle8** [byteManiak/MCQuake3#6]
**Issue**
The Rocket Launcher doesn't fire from the exact center - instead, it fires from the bottom right corner.

**How to reproduce**
Equip the Rocket Launcher. Aim down at your feet and rocket jump. Notice that the blast pushes you forward and to the left slightly.

**Comment by byteManiak** [comment]
Hi, thank you for raising this issue. The problem with this is that I made it so that weapons fire "from the hand" rather than from the centre. It's fairly trivial to fix this but then the rocket positioning will look wrong for the attacker's perspective.

**Comment by MiruCle8** [comment]
I think it'd make more sense to have it fire from the center regardless. It's something Quake does since Q3A and QL, and it doesn't affect gameplay much. I doubt it'd be very impactful in terms of visuals

Thank you for responding! 🙂
